name: trial1
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth:
  google_sign_in:
  cloud_firestore: ^0.13.0+1
  firebase_storage:
  fluttertoast:
  charts_flutter: ^0.10.0
  firebase_core: ^0.4.4
  firebase_messaging: ^6.0.15
  shared_preferences:
  image_picker:
  expandable:
  mongo_dart:
  about:
  cached_network_image:
  intl: ^0.15.7
  firebase_database:
  reference: ^0.1.4+1
  carousel_pro: ^1.0.0
  firebase_picture_uploader:
  provider:
  pinput: ^0.2.6
  get_it: ^6.0.0
  flutter_khalti: ^1.0.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons:
  carousel_slider: ^1.3.0
  transparent_image: ^0.1.0
  flutter_spinkit: ^4.1.2
  overlay_support:
  flutter_rating_bar:
  uuid: ^2.2.0
  font_awesome_flutter: 8.8.1
  firebase_image:
  flutter_typeahead: ^1.8.7
  change_app_package_name: ^0.1.2
  bubble:
  flutter_dialogflow: ^0.1.3
  flutter_launcher_icons: ^0.7.3
  flutter_launcher_name: ^0.0.1


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icons"
  ios: true
  image_path: "assets/images/logo.png"
  image_path_android: "assets/images/logo.png"

flutter_launcher_name:
  name: "Medhavi Cafeteria"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/chatbot.json
    - assets/camera.png
    - assets/services.json
    - assets/images/logo.png
    - assets/images/add.png
    - assets/images/user.png
    - assets/images/robot.png
    - assets/profile.jpg
    - assets/money.png
    - assets/khalti.png
    - assets/images/reset.png
    - assets/images/menus/ic_search_menu.png
    - assets/images/menus/ic_account.png
    - assets/images/menus/ic_cart.png
    - assets/images/menus/ic_home.png
    - assets/images/menus/ic_delete.png
    - assets/images/menus/ic_near_by.png
    - assets/images/menus/logo.png
    - assets/images/menus/ic_credit_card.png
    - assets/images/menus/ic_app_icon.png
    - assets/images/menus/ic_food_express.png
    - assets/images/menus/ic_app_icon_black.png
    - assets/profile.jpg
    - assets/images/topmenu/ic_burger.png
    - assets/images/topmenu/ic_cake.png
    - assets/images/topmenu/ic_ice_cream.png
    - assets/images/topmenu/ic_pasta.png
    - assets/images/topmenu/ic_pizza.png
    - assets/images/topmenu/ic_sushi.png
    - assets/images/topmenu/ic_soft_drink.png
    - assets/images/popular_foods/burger.png
    - assets/images/popular_foods/ic_popular_food_2.png
    - assets/images/popular_foods/ic_popular_food_3.png
    - assets/images/popular_foods/ic_popular_food_4.png
    - assets/images/popular_foods/ic_popular_food_5.png
    - assets/images/popular_foods/ic_popular_food_6.png
    - assets/images/bestfood/ic_best_food_1.jpeg
    - assets/images/bestfood/ic_best_food_2.jpeg
    - assets/images/bestfood/ic_best_food_3.jpeg
    - assets/images/bestfood/ic_best_food_4.jpeg
    - assets/images/bestfood/ic_best_food_5.jpeg
    - assets/images/bestfood/ic_best_food_6.jpeg
    - assets/images/bestfood/ic_best_food_7.jpeg
    - assets/images/bestfood/ic_best_food_8.jpeg
    - assets/images/bestfood/ic_best_food_9.jpeg
    - assets/images/bestfood/ic_best_food_10.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
